### ISSUE TITLE
Running Server on macOS Giver vnum Errors

### ISSUE THREAD

**Issue by datatypevoid** [nickgammon/tinymudserver#2]
Compiling on macOS Sierra seem to work fine, however when I start the server up, I get the following output:

```
[1] 91668
Tiny MUD server version 2.2.0
Bad vnum for exit w for room 1000
Bad vnum for exit n for room 1001
Bad vnum for exit e for room 1002
Bad vnum for exit e for room 1003
Bad vnum for exit s for room 1004
Bad vnum for exit w for room 1005
Accepting connections from port 4000
```

This seems irregular, and while connecting works fine, travelling to those rooms leaves you stuck in them.

**Comment by nickgammon** [comment]
I can't reproduce this on Ubuntu nor on Mac OS/X 10.7.5.

I suspect your line endings are causing this, because all it is doing is trying to read a line from the rooms.txt file, like this:

```
1000 
Starting room (room 1000).%rYou are standing in a fabulous, fabulous, exotic room, with all sorts of things that go 'hum' and 'plink' in the night.%r%rAs you glance around the room, you wonder what else might exist in this world.
n 1004 s 1001 e 1002 w 1003
```

In my Git config file I have this:

```git
core.autocrlf=false
```

Check this with:

```bash
git config --list
```

Try editing that file with a text editor that lets you play with line endings. They should be just \n at the end of the line.

**Comment by datatypevoid** [comment]
I have ensured that line endings are correct, manually converting them myself to be sure for my system, handwriting the file, et cetera. None of these seems to fix the problem.

**Comment by nickgammon** [comment]
Hmm. Your first error is on this line:

```
n 1004 s 1001 e 1002 w 1003
```

It only fails on the "west" exit which suggest that the line ending is the issue (it got 1004, 1001, 1002 OK).

I've added an improved error message (commit 3b88972) to help you work out what is going on. So you should see something like this:

```
Bad vnum 'foo' for exit w for room 1000
```

Where "foo" is the word it can't decode as a vnum.

**Comment by nickgammon** [comment]
I've modified the source slightly to not test for whitespace after the vnum. This may be causing the issue you are getting. Try recompiling (commit 1e42533).

**Comment by datatypevoid** [comment]
Sorry for the long delay, it builds fine now. Thanks for the help!
